// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9WyhV7tMVsETyXsrASEGMFKgirWic-jc',
    appId: '1:369564835534:web:2b8393bb75e32da1983a9f',
    messagingSenderId: '369564835534',
    projectId: 'car-culture-fyp',
    authDomain: 'car-culture-fyp.firebaseapp.com',
    storageBucket: 'car-culture-fyp.firebasestorage.app',
    measurementId: 'G-KPNFKZ3TXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQb0tMje6sU2oGybjIBnGXDSAs50F7Ss8',
    appId: '1:369564835534:android:9a1728a1333aa6d2983a9f',
    messagingSenderId: '369564835534',
    projectId: 'car-culture-fyp',
    storageBucket: 'car-culture-fyp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAABBQEbJ7up7pKZdvqBxb_jnzqSFk78vA',
    appId: '1:369564835534:ios:2e35231cfc7e89ae983a9f',
    messagingSenderId: '369564835534',
    projectId: 'car-culture-fyp',
    storageBucket: 'car-culture-fyp.firebasestorage.app',
    iosBundleId: 'com.example.carCultureFyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAABBQEbJ7up7pKZdvqBxb_jnzqSFk78vA',
    appId: '1:369564835534:ios:2e35231cfc7e89ae983a9f',
    messagingSenderId: '369564835534',
    projectId: 'car-culture-fyp',
    storageBucket: 'car-culture-fyp.firebasestorage.app',
    iosBundleId: 'com.example.carCultureFyp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9WyhV7tMVsETyXsrASEGMFKgirWic-jc',
    appId: '1:369564835534:web:80e65ba2720b7308983a9f',
    messagingSenderId: '369564835534',
    projectId: 'car-culture-fyp',
    authDomain: 'car-culture-fyp.firebaseapp.com',
    storageBucket: 'car-culture-fyp.firebasestorage.app',
    measurementId: 'G-3QQSF9NHEX',
  );
}
